const XLSX = require('xlsx');

const students = [
  {
    name: 'নাহু উমর',
    class: '১ম শ্রেণী',
    father: 'আঃ করিম',
    father_mobile: '01780162600',
    mother: 'ফাতেমা আক্তার',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '০২-০২-২০২০',
    student_mobile: '',
    village: 'দরগামহল্লা',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'আঃ করিম', relation: 'বাবা',
    prev_inst: 'অত্র মাদ্রাসা', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৮৬', form_no: '৪২', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '11.jpg',
  },
  {
    name: 'শাহ মাহ্দী',
    class: '১ম শ্রেণী',
    father: 'বাবলু মিয়া',
    father_mobile: '01712383376',
    mother: 'রাহা আক্তার',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '২৭-০৪-২০১৭',
    student_mobile: '',
    village: 'দরগামহল্লা',
    post: 'বড়বাজার',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'বাবলু মিয়া', relation: 'পিতা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৪৭', form_no: '৬৭', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '12.jpg',
  },
  {
    name: 'মুছতাহা আক্তার',
    class: '১ম শ্রেণী',
    father: 'মোহাদিব মিয়া',
    father_mobile: '01752926001',
    mother: 'বিনা আক্তার',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '০২-০৬-২০২০',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'মোহাদিব মিয়া', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৪৬', form_no: '৬০', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '13.jpg',
  },
  {
    name: 'আতিকুর রহমান',
    class: '১ম শ্রেণী',
    father: 'আবিদুর রহমান',
    father_mobile: '01750675425',
    mother: 'তারিণ আক্তার',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '০২-০৬-২০২০',
    student_mobile: '',
    village: 'কেলুরখ্যাপাই',
    post: 'সলাপাড়া',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'আবিদুর রহমান', relation: 'বাবা',
    prev_inst: '', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৫৫', form_no: '৩৩', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '14.jpg',
  },
  {
    name: 'রিহান আহমেদ',
    class: '১ম শ্রেণী',
    father: 'নানু মিয়া',
    father_mobile: '01774043580',
    mother: 'কুতিনা আক্তার',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '২৬-০২-২০১৯',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বড়বাজার',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'কুতিনা আক্তার', relation: 'মাতা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৫২', form_no: '৩২', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '15.jpg',
  },
  {
    name: 'আফাযুরুল আমিন নাদিম',
    class: '১ম শ্রেণী',
    father: 'মো: খলিল আমিন',
    father_mobile: '01730280452',
    mother: 'সাকিনা বিবি',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '২৬-০৫-২০১৯',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'মো: কাদের আলী', relation: 'দাদা',
    prev_inst: 'জামিয়া দারুল আরকাম', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '১০০০',
    dakhila: '০৬', form_no: '৭৩', notun_puraton: 'নতুন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '16.jpg',
  },
  {
    name: 'সামিয়া আক্তার',
    class: '১ম শ্রেণী',
    father: 'নাজমুল হক',
    father_mobile: '01746256732',
    mother: 'সুমি',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '২৪-০৭-২০১৯',
    student_mobile: '',
    village: 'দুপ্তারা',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'নাজমুল হক', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '১১০', form_no: '২১৪', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '17.jpg',
  },
  {
    name: 'মাহদী হুসাইন',
    class: '১ম শ্রেণী',
    father: 'নুরুল আমিন',
    father_mobile: '01712537575',
    mother: 'সুলতানা আক্তার',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '২৮-১১-২০১৮',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'নুরুল আমিন', relation: 'পিতা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '২০৫', form_no: '৭২', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '18.jpg',
  },
  {
    name: 'হুসামিন আক্তার',
    class: '১ম শ্রেণী',
    father: 'এনামুল হক',
    father_mobile: '01725274857',
    mother: 'রাহিদা আক্তার',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '০২-০২-২০১৯',
    student_mobile: '',
    village: 'ছুতপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'এনামুল হক', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৫২৭', form_no: '১১৭', notun_puraton: 'নতুন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '19.jpg',
  },
  {
    name: 'মাহিয়া ইসলাম',
    class: '১ম শ্রেণী',
    father: 'মো: দিদারুল ইসলাম',
    father_mobile: '01746795325',
    mother: 'মোছা: মরিয়ম',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '২৪-০৫-২০১৮',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'দিদারুল ইসলাম', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: '',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '১০৬', form_no: '১৬', notun_puraton: 'নতুন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '20.jpg',
  },
];

const rows = students.map(s => ({
  'নাম': s.name,
  'শ্রেণী': s.class,
  'পিতার নাম': s.father,
  'পিতার মোবাইল': s.father_mobile,
  'মাতার নাম': s.mother,
  'মাতার মোবাইল': s.mother_mobile,
  'লিঙ্গ': s.gender,
  'জন্মতারিখ': s.dob,
  'শিক্ষার্থীর মোবাইল': s.student_mobile,
  'বর্তমান গ্রাম': s.village,
  'বর্তমান ডাক': s.post,
  'বর্তমান উপজেলা': s.upazila,
  'বর্তমান জেলা': s.district,
  'স্থায়ী গ্রাম': s.perm_village,
  'স্থায়ী ডাক': s.perm_post,
  'স্থায়ী উপজেলা': s.perm_upazila,
  'স্থায়ী জেলা': s.perm_district,
  'অভিভাবকের নাম': s.guardian,
  'সম্পর্ক': s.relation,
  'আগের প্রতিষ্ঠান': s.prev_inst,
  'আগের শ্রেণী': s.prev_class,
  'বিভাগ': s.dept,
  'মাসিক ফি': s.fee,
  'দাখিলা নং': s.dakhila,
  'ফর্ম নং': s.form_no,
  'নতুন/পুরাতন': s.notun_puraton,
  'শিক্ষাবর্ষ হিজরি': s.hijri,
  'শিক্ষাবর্ষ ইংরেজি': s.english,
  'ছবির ফাইল': s.photo,
}));

const ws = XLSX.utils.json_to_sheet(rows);
ws['!cols'] = Array(29).fill({wch: 18});

const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, '১ম শ্রেণী scan');

const outPath = 'C:\\Users\\Tayef\\Downloads\\1st papre\\protishthan-complete-v211\\Form\\১ম শ্রেনী\\১ম শ্রেণী - scan 11-20.xlsx';
XLSX.writeFile(wb, outPath);
console.log('Done:', outPath);
