const XLSX = require('xlsx');

// Format matches students_FINAL_fixed.xlsx exactly
// Columns: নাম,শ্রেণী,পিতার নাম,পিতার মোবাইল,মাতার নাম,মাতার মোবাইল,লিঙ্গ,জন্মতারিখ,
//          শিক্ষার্থীর মোবাইল,বর্তমান গ্রাম,বর্তমান ডাক,বর্তমান উপজেলা,বর্তমান জেলা,
//          স্থায়ী গ্রাম,স্থায়ী ডাক,স্থায়ী উপজেলা,স্থায়ী জেলা,
//          অভিভাবকের নাম,সম্পর্ক,আগের প্রতিষ্ঠান,আগের শ্রেণী,বিভাগ,মাসিক ফি,
//          দাখিলা নং,ফর্ম নং,নতুন/পুরাতন,শিক্ষাবর্ষ হিজরি,শিক্ষাবর্ষ ইংরেজি,ছবির ফাইল

const students = [
  {
    name: 'জান্নাতুল ফেরদৌস রুকাইয়া',
    class: '১ম শ্রেণী',
    father: 'রাইমুল ইসলাম',
    father_mobile: '০১৬৬২৯৭৩৫৪২ (যাচাই করুন)',
    mother: 'মাহতাবা সুলতানা',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '২৭-০৬-২০১৭',
    student_mobile: '',
    village: 'নাজের খানা',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'রাইমুল ইসলাম', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু খ',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৭২০', form_no: '৯৫০', notun_puraton: 'নতুন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '01.jpeg',
  },
  {
    name: 'সুমাইয়া জাহান মিম',
    class: '১ম শ্রেণী',
    father: 'জুনাইদ আহমেদ',
    father_mobile: '০১৭৩৮৭৩৫২২৫ (যাচাই করুন)',
    mother: 'নাজমা আক্তার',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '০২-০২-২০১৯',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'জুনাইদ আহমেদ', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '২০২', form_no: '২৩০', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '02.jpeg',
  },
  {
    name: 'ফারমিদা আখতার',
    class: '১ম শ্রেণী',
    father: 'ফজুল হক',
    father_mobile: '০১৭৫৩৪৮১৯৮৩ (যাচাই করুন)',
    mother: 'মোছা. তানিয়া আক্তার',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '০৬-০৭-২০১৮',
    student_mobile: '',
    village: 'চৌগলিয়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'ফজুল হক', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '১৬০', form_no: '৯৯', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '03.jpeg',
  },
  {
    name: 'সাদিয়া আখতার',
    class: '১ম শ্রেণী',
    father: 'মৃত: রাকিব মনির',
    father_mobile: '',
    mother: 'লিপি',
    mother_mobile: '০১৭৪৫৬৩১২২৫ (যাচাই করুন)',
    gender: 'মেয়ে',
    dob: '০৭-০৬-২০১৯',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বড়বাজার',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'লিপি', relation: 'মাতা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৪০', form_no: '৬৩', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '04.jpeg',
  },
  {
    name: 'মাছহারুল ইসলাম লাবীব',
    class: '১ম শ্রেণী',
    father: 'মানিরুল ইসলাম',
    father_mobile: '০১৭২৫৪০৬৭৮৫ (যাচাই করুন)',
    mother: 'মারজানা আক্তার',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '২৪-০৭-২০১৯',
    student_mobile: '',
    village: 'দরগামহল্লা',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'মানিরুল ইসলাম', relation: 'পিতা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '২৫০', form_no: '২৭৫', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '05.jpeg',
  },
  {
    name: 'সাগর আখতার (যাচাই করুন)',
    class: '১ম শ্রেণী',
    father: 'আরমান ভূইয়া',
    father_mobile: '০১৫৫৩৪২৩১২২ (যাচাই করুন)',
    mother: '',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '১৭-০২-২০২০',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'আরমান ভূইয়া', relation: 'বাবা',
    prev_inst: '', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৫১', form_no: '৬২', notun_puraton: 'নতুন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '06.jpeg',
  },
  {
    name: '(ছবি ঘোরানো — যাচাই করুন)',
    class: '১ম শ্রেণী',
    father: '', father_mobile: '', mother: '', mother_mobile: '',
    gender: '', dob: '', student_mobile: '',
    village: '', post: '', upazila: 'বানিয়াচং', district: 'হবিগঞ্জ',
    perm_village: '', perm_post: '', perm_upazila: '', perm_district: '',
    guardian: '', relation: '',
    prev_inst: '', prev_class: '',
    dept: 'নূরানী', fee: '',
    dakhila: '', form_no: '', notun_puraton: '',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '07.jpeg',
  },
  {
    name: 'মুকাররম হুসাইন',
    class: '১ম শ্রেণী',
    father: 'মো: মোজাহিদ মিয়া',
    father_mobile: '০১৫৭৫৬০২৫৫৪ (যাচাই করুন)',
    mother: 'মোছা: হাদিয়া আক্তার',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '২৮-১১-২০১৮ (যাচাই করুন)',
    student_mobile: '',
    village: 'নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'মোজাহিদ মিয়া', relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '০৬০', form_no: '১৫৬', notun_puraton: 'নতুন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '8.jpg',
  },
  {
    name: 'জুবায়ের আহমেদ',
    class: '১ম শ্রেণী',
    father: 'আহমেদ (পুরো নাম যাচাই করুন)',
    father_mobile: '০১৬২৫৩৫০১৭৫ (যাচাই করুন)',
    mother: '',
    mother_mobile: '',
    gender: 'ছেলে',
    dob: '১০-১০-২০১৮',
    student_mobile: '',
    village: 'পূর্ব নন্দীপাড়া',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'জুবায়ের আহমেদ', relation: 'ভাই',
    prev_inst: 'না', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৭৬৪', form_no: '২২৭', notun_puraton: 'নতুন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '9.jpg',
  },
  {
    name: 'সাহিরা তাবাস্সুম',
    class: '১ম শ্রেণী',
    father: 'তাহের উদ্দিন (যাচাই করুন)',
    father_mobile: '০১৭৬৫০৩৪৩৫২ (যাচাই করুন)',
    mother: 'রুকেদা বেগম',
    mother_mobile: '',
    gender: 'মেয়ে',
    dob: '২২-০৫-২০১৮',
    student_mobile: '',
    village: 'দরগামহল্লা',
    post: 'বানিয়াচং',
    upazila: 'বানিয়াচং',
    district: 'হবিগঞ্জ',
    perm_village: 'ঐ', perm_post: 'ঐ', perm_upazila: 'ঐ', perm_district: 'ঐ',
    guardian: 'তাহের উদ্দিন',  relation: 'বাবা',
    prev_inst: 'অত্র জামেয়া', prev_class: 'শিশু ক',
    dept: 'নূরানী', fee: '২০০০',
    dakhila: '৫০', form_no: '৩০', notun_puraton: 'পুরাতন',
    hijri: '১৪৪৭/৪৮', english: '২০২৬/২৭', photo: '10.jpg',
  },
];

const rows = students.map(s => ({
  'নাম': s.name,
  'শ্রেণী': s.class,
  'পিতার নাম': s.father,
  'পিতার মোবাইল': s.father_mobile,
  'মাতার নাম': s.mother,
  'মাতার মোবাইল': s.mother_mobile,
  'লিঙ্গ': s.gender,
  'জন্মতারিখ': s.dob,
  'শিক্ষার্থীর মোবাইল': s.student_mobile,
  'বর্তমান গ্রাম': s.village,
  'বর্তমান ডাক': s.post,
  'বর্তমান উপজেলা': s.upazila,
  'বর্তমান জেলা': s.district,
  'স্থায়ী গ্রাম': s.perm_village,
  'স্থায়ী ডাক': s.perm_post,
  'স্থায়ী উপজেলা': s.perm_upazila,
  'স্থায়ী জেলা': s.perm_district,
  'অভিভাবকের নাম': s.guardian,
  'সম্পর্ক': s.relation,
  'আগের প্রতিষ্ঠান': s.prev_inst,
  'আগের শ্রেণী': s.prev_class,
  'বিভাগ': s.dept,
  'মাসিক ফি': s.fee,
  'দাখিলা নং': s.dakhila,
  'ফর্ম নং': s.form_no,
  'নতুন/পুরাতন': s.notun_puraton,
  'শিক্ষাবর্ষ হিজরি': s.hijri,
  'শিক্ষাবর্ষ ইংরেজি': s.english,
  'ছবির ফাইল': s.photo,
}));

const ws = XLSX.utils.json_to_sheet(rows);

// Column widths
ws['!cols'] = [
  {wch:8},{wch:10},{wch:12},{wch:12},{wch:28},{wch:16},{wch:22},{wch:22},
  {wch:18},{wch:14},{wch:14},{wch:12},{wch:22},{wch:10},{wch:22},{wch:18},{wch:14},{wch:10}
];

const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, '১ম শ্রেণী scan');

const outPath = 'C:\\Users\\Tayef\\Downloads\\1st papre\\protishthan-complete-v211\\Form\\১ম শ্রেনী\\১ম শ্রেণী - scan 01-10.xlsx';
XLSX.writeFile(wb, outPath);
console.log('Done:', outPath);
